### ISSUE TITLE
Incorrect example in README

### ISSUE THREAD

**Issue by sofer** [mislav/contacts#1]
Line 15 of README.rdoc:
 gmail = Contacts::Google.new('example@gmail.com', params[:token])
could be replaced with:
 gmail = Contacts::Google.new(params[:token])

This error is corrected in Contacts::Google, but lazy people (like me) may not always get past the README.

**Comment by mislav** [comment]
update Contacts::Google docs

closed by f33f242f39d1cb04bc2484de3c744a4d7414aeb4
